#!/usr/bin/env php
<?php

use Infrastructure\DebugBar\DebugBarProvider;
use Oxygen\Providers\Console\Console;
use Oxygen\Providers\Console\ConsoleProvider;
use Oxygen\Providers\Database\Doctrine\DoctrineProvider;
use Zend\Diactoros\ServerRequestFactory;

$app = require_once "application.php";
$app->handle(ServerRequestFactory::fromGlobals());
$app->use(new ConsoleProvider());
/***
 * adding doctrine after the console is loaded to make sure that doctrine commands loads
 */
$doctrineProvider = $app->get(DoctrineProvider::class);
$app->use($doctrineProvider);
$app->use(new DebugBarProvider());
$console = $app->get(Console::class)->getApplication();
$console->run();
